// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYXIci7mPp2a2TbTC9HolQUotGNL8v1OM',
    appId: '1:1049398174478:web:bdd647ee4b1bba366eed5f',
    messagingSenderId: '1049398174478',
    projectId: 'chat-app-c3903',
    authDomain: 'chat-app-c3903.firebaseapp.com',
    storageBucket: 'chat-app-c3903.appspot.com',
    measurementId: 'G-XJWGHXJW1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVahTiPNMHRJ3AuyKQDLVXe91Di6zQ1UI',
    appId: '1:1049398174478:android:e18f35aee88e2f2d6eed5f',
    messagingSenderId: '1049398174478',
    projectId: 'chat-app-c3903',
    storageBucket: 'chat-app-c3903.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIYU_LENAZnX_EIAClBTYYuwCLt8xCmK4',
    appId: '1:1049398174478:ios:9a37e4a1ee8f68526eed5f',
    messagingSenderId: '1049398174478',
    projectId: 'chat-app-c3903',
    storageBucket: 'chat-app-c3903.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIYU_LENAZnX_EIAClBTYYuwCLt8xCmK4',
    appId: '1:1049398174478:ios:06b142430b8290926eed5f',
    messagingSenderId: '1049398174478',
    projectId: 'chat-app-c3903',
    storageBucket: 'chat-app-c3903.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
